language: objective-c
osx_image: xcode7
branches:
  only:
    - master
before_install:
  - gem install xcpretty
script:
- set -o pipefail
- xcodebuild -project Example/DynamicButtonExample.xcodeproj -scheme DynamicButtonTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild -project Example/DynamicButtonExample.xcodeproj -scheme DynamicButtonExampleUITests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -c
