language: objective-c
osx_image: xcode7.1
branches:
  only:
    - master
before_install:
  - gem install xcpretty
script:
  - set -o pipefail
  - xcodebuild -project Example/DynamicButtonExample.xcodeproj -scheme DynamicButtonTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6,OS=9.0" ONLY_ACTIVE_ARCH=YES test | xcpretty -c
  - xcodebuild -project Example/DynamicButtonExample.xcodeproj -scheme DynamicButtonExampleUITests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6,OS=9.0" ONLY_ACTIVE_ARCH=YES test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
